### ISSUE TITLE
Evaluation 1

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/jqfundamentals#13]
User's todolist
In this application we'll maintain users and their todos. There will be two forms, one for creating users and other for creating todos & assigning them to users.

There will be two buttons 'Create User' and 'Create Todo', they will display respective forms.

User Form: It takes User's Name as input and display it in the User's column with it's initial remaining To-Do count as 0. Name should not be blank and should be unique.
To-Do Form: It takes todo as input with the assignee name from a select box which contains names of already existing user. Todo form will be displayed only if there is atleast one user. It will alert an error message if somebody clicks on 'create todo' button and no user exists.
Once a task/todo is added, increment the count of remaining todos of the respective user who this task has been assigned to.

Todo is displayed in the todo column with a check-box.

When this checkbox is checked then strike-through the todo which means that todo is done and the remaining todo count is decremented by 1 of the user. And if it unchecked increment the count by 1 again.

Refer to the below given doc for layout, design and steps.
https://dl.dropboxusercontent.com/u/29811381/VTAPP/jQuery/user-todolist/ToDoApp.pdf

https://github.com/wilsonokibe/jqfundamentals/tree/master/JQUERY_EXERCISES/todo_Evaluation

**Comment by segunadeleye** [comment]
Here are some little observations.

Functionality review

I should not be able to save empty todo field
The count of todos for each user should appear immediately the user is created. That is defaults to 0.

User field disappears if input is not valid. Fix this

I was able to change the display property for the todo field and create a todo. Can you fix that. I should not be able to create a todo until at least a user is created

Users' names must be unique

Move the checbox to the left. It should not be on the right

Todo field and User field should not appear at the same time. They should appear one at a time.

Code Review

Have all your event listeners in a bind events method

Validator class should be in another file.

`validateName()` should be in UserTodo class

Can we make `validateName()` return true or false instead of returning false or the name.

`this.nameArray` should be declared within `init()`

In `countTotalAssigned()`, you don't have to loop to get task count for a user. You should be able get a count of the unchecked boxes based on the data-id attribute. Hence no need for `idCount = todoCount - idCount` :114

There is a better way to get/set the value of a data attribute. check out `data()`

Why use `match`. Will `test` not do the job?

Why did you create a UserTodo object within `Validator` class? There is no need for that.

What if you use `else`? :154

Why `let count = 0`. Remove all unused variables :143

You can simply append the new user to the select list instead of creating the options all over again after every user is created.

Is there really a need to set the id of the todo checkboxes?

**Comment by wilsonokibe** [comment]
fixed

**Comment by wilsonokibe** [comment]
update

**Comment by segunadeleye** [comment]
Looks good now
